worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    server {
        listen       3052;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;

        location = / {
            try_files /index.html =404;
        }

        location /assets/ {
            try_files $uri =404;
        }

        location ~ ^/(work-orders|master-data|employees|shifts|work-calendar|console/mes)(/.*)?$ {
            try_files $uri $uri/ /index.html;
        }

        location ~ ^/analytics(/.*)?$ {
            try_files $uri $uri/ /index.html;
        }

        location / {
            error_page 404 /index.html;
            try_files $uri $uri/ =404;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
