export const qk = {
  warehouses: ['wms', 'warehouses'] as const,
  warehouse: (id: string) => ['wms', 'warehouse', id] as const,
  zones: (warehouseId: string) => ['wms', 'zones', warehouseId] as const,
  zone: (id: string) => ['wms', 'zone', id] as const,
  locations: ['wms', 'locations'] as const,
  zoneLocations: (zoneId: string) => ['wms', 'locations', zoneId] as const,
  location: (id: string) => ['wms', 'location', id] as const,
  bins: (locationId: string) => ['wms', 'bins', locationId] as const,
  itemUom: ['wms', 'item-uom'] as const,
  balances: (filter = '') => ['wms', 'balances', filter] as const,
  movements: (filter = '') => ['wms', 'movements', filter] as const,
  receipt: (id: string) => ['wms', 'receipt', id] as const,
  request: (id: string) => ['wms', 'request', id] as const,
};
