import React from 'react';
import { MoreHorizontal, Pencil, Plus, RefreshCw, Trash2, Eye } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { useI18n, useLocalizedText } from '@mom-platform/i18n-ui-shared';
import { Button, Input, Confirmation } from '../../components/ui';
import { BaseDataTable, BaseModal, type BaseDataTableColumn } from '../../components/base';
import { LocalizedTextFields, emptyLocalized } from '../../components/LocalizedTextFields';
import { fetchResource, postResource, putResource, deleteResource } from '../../lib/masterDataApi';

type MaterialGroup = { master_id: string; code: string; name: any; description?: any; item_reference_count?: number; revision_reference_count?: number };

function errorText(error: any, t: (key: string) => string) {
  const code = String(error?.code || '').trim();
  return t(`materialGroups.errors.${code}`) !== `materialGroups.errors.${code}` ? t(`materialGroups.errors.${code}`) : String(error?.message || t('common.unknownError'));
}

export const MaterialGroupManagementScreen: React.FC = () => {
  const { user } = useAuth(); const { t } = useI18n(); const text = useLocalizedText();
  const [rows, setRows] = React.useState<MaterialGroup[]>([]); const [loading, setLoading] = React.useState(true); const [search, setSearch] = React.useState('');
  const [editing, setEditing] = React.useState<MaterialGroup | null>(null); const [detail, setDetail] = React.useState<MaterialGroup | null>(null); const [confirm, setConfirm] = React.useState<MaterialGroup | null>(null); const [menu, setMenu] = React.useState<string | null>(null); const [saving, setSaving] = React.useState(false);
  const load = React.useCallback(async () => { setLoading(true); try { setRows(await fetchResource('material-groups', user, `?limit=500${search ? `&search=${encodeURIComponent(search)}` : ''}`)); } catch (error: any) { toast.error(errorText(error, t)); } finally { setLoading(false); } }, [search, t, user]);
  React.useEffect(() => { void load(); }, [load]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!editing) return; setSaving(true); try { if (editing.master_id) await putResource('material-groups', editing.master_id, editing, user); else await postResource('material-groups', editing, user); toast.success(t('materialGroups.saved')); setEditing(null); await load(); } catch (error: any) { toast.error(errorText(error, t)); } finally { setSaving(false); } };
  const remove = async () => { if (!confirm) return; try { await deleteResource('material-groups', confirm.master_id, user); toast.success(t('materialGroups.deleted')); setConfirm(null); await load(); } catch (error: any) { toast.error(errorText(error, t)); } };
  const columns: BaseDataTableColumn<MaterialGroup>[] = [
    { accessorKey: 'code', header: t('materialGroups.code'), cell: ({ row }) => <span className="font-mono font-bold text-amber-300">{row.original.code}</span> },
    { accessorKey: 'name', header: t('materialGroups.name'), cell: ({ row }) => <span>{text(row.original.name as any) || row.original.code}</span> },
    { id: 'references', header: t('materialGroups.references'), cell: ({ row }) => <span>{Number(row.original.item_reference_count || 0) + Number(row.original.revision_reference_count || 0)}</span> },
    { id: 'actions', header: t('common.actions'), enableSorting: false, cell: ({ row }) => <div className="relative text-right"><Button type="button" variant="ghost" size="icon" aria-label={t('materialGroups.actions')} onClick={(event) => { event.stopPropagation(); setMenu(menu === row.original.master_id ? null : row.original.master_id); }}><MoreHorizontal className="h-5 w-5" /></Button>{menu === row.original.master_id && <div className="absolute right-2 top-11 z-[300] min-w-48 rounded-md border border-border bg-surface p-1 text-left shadow-xl"><button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm hover:bg-hover" onClick={() => { setDetail(row.original); setMenu(null); }}><Eye className="h-4 w-4" />{t('materialGroups.view')}</button><button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm hover:bg-hover disabled:opacity-50" disabled={Number(row.original.item_reference_count || 0) + Number(row.original.revision_reference_count || 0) > 0} onClick={() => { setEditing({ ...row.original, name: row.original.name || emptyLocalized(), description: row.original.description || emptyLocalized() }); setMenu(null); }}><Pencil className="h-4 w-4" />{t('materialGroups.edit')}</button><button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-destructive hover:bg-destructive/10 disabled:opacity-50" disabled={Number(row.original.item_reference_count || 0) + Number(row.original.revision_reference_count || 0) > 0} onClick={() => { setConfirm(row.original); setMenu(null); }}><Trash2 className="h-4 w-4" />{t('materialGroups.delete')}</button></div>}</div> },
  ];
  return <div className="mes-page"><div className="mes-page-header"><div><h1 className="text-xl font-bold text-foreground">{t('materialGroups.title')}</h1><p className="text-xs text-muted-foreground">{t('materialGroups.subtitle')}</p></div><div className="flex gap-2"><Button variant="secondary" size="icon" onClick={() => void load()}><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /></Button><Button onClick={() => setEditing({ master_id: '', code: '', name: emptyLocalized(), description: emptyLocalized() })}><Plus className="h-4 w-4" />{t('materialGroups.create')}</Button></div></div><BaseDataTable data={rows} columns={columns} loading={loading} search={search} onSearchChange={setSearch} getRowId={(row) => row.master_id} stickyHeader />
    <BaseModal open={Boolean(editing)} title={editing?.master_id ? t('materialGroups.edit') : t('materialGroups.create')} onClose={() => setEditing(null)} size="md" loading={saving} footer={<><Button variant="secondary" onClick={() => setEditing(null)}>{t('common.cancel')}</Button><Button onClick={(event) => void save(event as any)} disabled={saving}>{t('common.save')}</Button></>}><form onSubmit={save} className="space-y-4"><label className="block space-y-1 text-sm"><span>{t('materialGroups.code')} *</span><Input value={editing?.code || ''} onChange={(event) => setEditing({ ...(editing as MaterialGroup), code: event.target.value.toUpperCase() })} required /></label><LocalizedTextFields label={t('materialGroups.name')} value={editing?.name || emptyLocalized()} onChange={(name) => setEditing({ ...(editing as MaterialGroup), name })} required /><LocalizedTextFields label={t('materialGroups.description')} value={editing?.description || emptyLocalized()} onChange={(description) => setEditing({ ...(editing as MaterialGroup), description })} multiline /></form></BaseModal>
    <BaseModal open={Boolean(detail)} title={detail?.code || ''} onClose={() => setDetail(null)} size="sm"><div className="space-y-3"><p className="text-lg font-semibold">{detail && text(detail.name as any)}</p><p className="text-sm text-muted-foreground">{detail && text(detail.description as any) || t('common.notAvailable')}</p><p className="text-sm">{t('materialGroups.references')}: {Number(detail?.item_reference_count || 0) + Number(detail?.revision_reference_count || 0)}</p></div></BaseModal><Confirmation open={Boolean(confirm)} title={t('materialGroups.delete')} description={t('materialGroups.deleteConfirm')} confirmLabel={t('materialGroups.delete')} cancelLabel={t('common.cancel')} destructive onClose={() => setConfirm(null)} onConfirm={() => void remove()} />
  </div>;
};
