import React, { useEffect, useState } from 'react';
import { ArrowLeft, Plus, Save, Trash2 } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useI18n, useLocalizedText } from '@mom-platform/i18n-ui-shared';
import { fetchResource, postResource, masterDataBaseUrl, authHeaders } from '../../lib/masterDataApi';
import { Button, Confirmation, SelectBase } from '../../components/ui';
import { toast } from 'sonner';

function text(value: unknown): string { if (typeof value === 'string') return value; if (!value || typeof value !== 'object') return ''; const item = value as Record<string, unknown>; return String(item.vi || item.en || item.ja || item.ko || ''); }
function dateValue(value: unknown): string { return value ? String(value).slice(0, 10) : ''; }

export const RoutingOperationsScreen: React.FC = () => {
  const { id } = useParams(); const { user } = useAuth(); const { t } = useI18n(); const localizedText = useLocalizedText();
  const [routing, setRouting] = useState<any>(null); const [operations, setOperations] = useState<any[]>([]); const [workCenters, setWorkCenters] = useState<any[]>([]); const [workerSkills, setWorkerSkills] = useState<any[]>([]); const [rows, setRows] = useState<any[]>([]); const [saving, setSaving] = useState(false); const [removeIndex, setRemoveIndex] = useState<number | null>(null);
  const [form, setForm] = useState({ operation_id: '', work_center_id: '', seq: 10, predecessor_seq: '', worker_skill_requirements: [] as any[] });

  const loadDefaults = async (operationId: string) => {
    if (!operationId) return;
    const response = await fetch(`${masterDataBaseUrl()}/operations/${operationId}/worker-skill-requirements`, { headers: authHeaders(user) }); const payload = await response.json().catch(() => ({}));
    if (response.ok) setForm((current) => ({ ...current, worker_skill_requirements: (payload.data || []).map((item: any) => ({ ...item, inherited: true, effective_from: dateValue(item.effective_from), effective_to: dateValue(item.effective_to), status: 'Active' })) }));
  };
  const load = async () => {
    if (!id) return;
    try {
      const [headers, operationRows, wcRows, routeRows, skillRows] = await Promise.all([fetchResource('routing-headers', user), fetchResource('operations', user), fetchResource('work-centers', user), fetchResource('routing-operations', user, '?limit=500'), fetchResource('worker-skills', user)]);
      setRouting(headers.find((row: any) => row.master_id === id)); setOperations(operationRows); setWorkCenters(wcRows); setWorkerSkills(skillRows.filter((skill: any) => skill.scope === 'Employee' && skill.lifecycle_status !== 'Inactive' && skill.lifecycle_status !== 'Obsolete')); setRows(routeRows.filter((row: any) => row.routing_header_id === id).sort((a: any, b: any) => Number(a.seq) - Number(b.seq)));
      setForm((current) => ({ ...current, operation_id: current.operation_id || operationRows[0]?.master_id || '', work_center_id: current.work_center_id || wcRows[0]?.master_id || '' }));
    } catch (error: any) { toast.error(error.message); }
  };
  useEffect(() => { void load(); }, [id, user?.userId]);
  const updateRequirement = (index: number, key: string, value: any) => setForm((current) => ({ ...current, worker_skill_requirements: current.worker_skill_requirements.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value, inherited: false } : item) }));
  const addRequirement = () => setForm((current) => ({ ...current, worker_skill_requirements: [...current.worker_skill_requirements, { skill_id: workerSkills[0]?.master_id || '', minimum_level: 'L1', required_persons: 1, mandatory_flag: true, effective_from: new Date().toISOString().slice(0, 10), effective_to: '', status: 'Active', inherited: false }] }));
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); if (!form.operation_id || !form.work_center_id) return; setSaving(true);
    try {
      const operation = operations.find((row) => row.master_id === form.operation_id); const created = await postResource('routing-operations', { code: `${routing?.code || 'ROUTING'}-${String(form.seq).padStart(3, '0')}`, name: localizedText(operation?.name) || operation?.code || 'Operation', routing_header_id: id, operation_id: form.operation_id, work_center_id: form.work_center_id, seq: Number(form.seq), predecessor_seq: form.predecessor_seq ? Number(form.predecessor_seq) : null }, user);
      const routingOperationId = created.master_id || created.data?.master_id; const response = await fetch(`${masterDataBaseUrl()}/routing-operations/${routingOperationId}/worker-skill-requirements`, { method: 'PUT', headers: { ...authHeaders(user), 'Content-Type': 'application/json' }, body: JSON.stringify({ requirements: form.worker_skill_requirements }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || payload.error || 'Worker skill requirements could not be saved');
      toast.success(t('routing.operationAdded')); await load();
    } catch (error: any) { toast.error(error.message); } finally { setSaving(false); }
  };
  return <div className="mx-auto max-w-6xl space-y-6">
    <div className="flex items-center justify-between"><Link to="/master-data/routings" className="inline-flex items-center gap-2 text-sm text-action"><ArrowLeft className="h-4 w-4" />{t('routing.title')}</Link></div>
    <div className="mes-page-header"><div><h1 className="text-xl font-bold text-foreground">{routing?.code || t('routing.title')}</h1><p className="text-sm text-muted-foreground">{text(routing?.name)}</p><p className="text-xs text-muted-foreground">{text(routing?.description)}</p></div></div>
    <div className="overflow-hidden rounded-md border border-border bg-surface"><table className="mes-table"><thead><tr><th>{t('mbom.seq')}</th><th>{t('routing.operation')}</th><th>{t('routing.workCenter')}</th><th>{t('routing.confirmation')}</th><th>{t('routing.scan')}</th><th>{t('routing.outputLabel')}</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.master_id}><td className="font-mono">{index + 1}</td><td><div className="font-semibold">{row.operation_code}</div><div className="text-xs text-muted-foreground">{text(row.operation_name)}</div><div className="text-xs text-muted-foreground">{text(row.operation_description)}</div></td><td><div>{row.work_center_code}</div><div className="text-xs text-muted-foreground">{text(row.work_center_name)}</div></td><td>{row.confirmation_mode}</td><td>{row.requires_material_scan ? t('common.yes') : t('common.no')}</td><td>{row.requires_output_label ? t('common.yes') : t('common.no')}</td></tr>)}</tbody></table>{rows.length === 0 && <div className="p-8 text-center text-muted-foreground">{t('routing.noOperations')}</div>}</div>
    <form onSubmit={submit} className="space-y-4 rounded-md border border-border bg-surface p-6"><div className="grid gap-4 sm:grid-cols-4"><label className="space-y-1"><span className="text-sm text-foreground">{t('routing.operation')} *</span><SelectBase required value={form.operation_id} onValueChange={(value) => { setForm({ ...form, operation_id: value }); void loadDefaults(value); }} options={operations.map((row) => ({ value: row.master_id, label: `${row.code} — ${text(row.name)}` }))} aria-label={t('routing.operation')} /></label><label className="space-y-1"><span className="text-sm text-foreground">{t('routing.workCenter')} *</span><SelectBase required value={form.work_center_id} onValueChange={(value) => setForm({ ...form, work_center_id: value })} options={workCenters.map((row) => ({ value: row.master_id, label: `${row.code} — ${text(row.name)}` }))} aria-label={t('routing.workCenter')} /></label><label className="space-y-1"><span className="text-sm text-foreground">{t('mbom.seq')} *</span><input required type="number" min="1" value={form.seq} onChange={(e) => setForm({ ...form, seq: Number(e.target.value) })} className="w-full rounded-md border border-input bg-input p-3 text-foreground" /></label><label className="space-y-1"><span className="text-sm text-foreground">{t('routing.predecessor')}</span><input type="number" min="1" value={form.predecessor_seq} onChange={(e) => setForm({ ...form, predecessor_seq: e.target.value })} className="w-full rounded-md border border-input bg-input p-3 text-foreground" /></label></div>
      <section className="space-y-3 border-t border-border pt-4"><div><h2 className="font-bold">{t('routing.workerRequirements')}</h2><p className="text-sm text-muted-foreground">{t('routing.workerRequirementsHelp')}</p></div>{form.worker_skill_requirements.map((requirement, index) => <div key={requirement.master_id || index} className="grid gap-3 rounded border border-border p-3 md:grid-cols-[minmax(0,1fr)_120px_110px_110px_40px]"><div><SelectBase value={requirement.skill_id} onValueChange={(value) => updateRequirement(index, 'skill_id', value)} options={workerSkills.map((skill) => ({ value: skill.master_id, label: text(skill.name) || skill.code, secondaryLabel: skill.code }))} aria-label={t('operationCatalog.workerSkill')} required /><span className="text-xs text-muted-foreground">{requirement.inherited ? t('routing.inheritedFromOperation') : t('routing.routingOverride')}</span></div><SelectBase value={requirement.minimum_level} onValueChange={(value) => updateRequirement(index, 'minimum_level', value)} options={['Basic', 'L1', 'L2', 'L3', 'L4', 'L5'].map((value) => ({ value, label: value }))} aria-label={t('operationCatalog.minimumLevel')} required /><input type="number" min="1" step="1" value={requirement.required_persons} onChange={(event) => updateRequirement(index, 'required_persons', Number(event.target.value))} aria-label={t('operationCatalog.requiredPersons')} className="rounded-md border border-input bg-input p-2 text-foreground" required /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={requirement.mandatory_flag !== false} onChange={(event) => updateRequirement(index, 'mandatory_flag', event.target.checked)} />{t('operationCatalog.mandatory')}</label><Button type="button" variant="ghost" size="icon" title={t('common.remove')} onClick={() => setRemoveIndex(index)}><Trash2 className="h-4 w-4" /></Button></div>)}<Button type="button" variant="outline" onClick={addRequirement}><Plus className="h-4 w-4" />{t('operationCatalog.addWorkerRequirement')}</Button></section>
      <div className="flex justify-end"><Button type="submit" disabled={saving}><Save className="h-4 w-4" />{t('routing.addOperation')}</Button></div>
    </form>
    <Confirmation open={removeIndex !== null} title={t('routing.removeWorkerRequirement')} description={t('routing.removeWorkerRequirementConfirm')} confirmLabel={t('common.remove')} cancelLabel={t('common.cancel')} destructive onClose={() => setRemoveIndex(null)} onConfirm={() => { if (removeIndex !== null) setForm((current) => ({ ...current, worker_skill_requirements: current.worker_skill_requirements.filter((_item, index) => index !== removeIndex) })); setRemoveIndex(null); }} />
  </div>;
};
