import React from 'react';
import { Plus, RefreshCw, Ruler, Eye, Pencil, Power, Trash2, MoreHorizontal } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { useI18n, useLocalizedText } from '@mom-platform/i18n-ui-shared';
import { Button, Card, Confirmation, Input, Modal, SelectBase } from '../../components/ui';
import { LocalizedTextFields, emptyLocalized, type LocalizedValues } from '../../components/LocalizedTextFields';
import { fetchResource, postResource, putResource, deleteResource } from '../../lib/masterDataApi';
import { uomLabel, type UomRecord } from '../../components/UomSelector';
import { DecimalInput } from '../../components/DecimalInput';

const TYPES = ['Count', 'Length', 'Area', 'Weight', 'Volume', 'Time'];
const blank = () => ({ code: '', name: emptyLocalized(), description: emptyLocalized(), uom_class: 'Count', decimal_precision: 0, allow_fraction: false, lifecycle_status: 'Draft' });

function translateUomError(error: any, t: (key: string, params?: Record<string, string | number>) => string): string {
  const code = String(error?.code || '').trim();
  const key = code.startsWith('uom.errors.') ? code : `uom.errors.${code}`;
  return t(key, { defaultValue: error?.message || t('common.unknownError') });
}

export const UomManagementScreen: React.FC = () => {
  const { user } = useAuth(); const { t } = useI18n(); const text = useLocalizedText();
  const [rows, setRows] = React.useState<UomRecord[]>([]); const [loading, setLoading] = React.useState(true); const [search, setSearch] = React.useState('');
  const [editing, setEditing] = React.useState<any>(null); const [detail, setDetail] = React.useState<any>(null); const [confirm, setConfirm] = React.useState<any>(null); const [actionMenuId, setActionMenuId] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { setLoading(true); try { setRows(await fetchResource('uoms', user, `?limit=500${search ? `&search=${encodeURIComponent(search)}` : ''}`)); } catch (e: any) { toast.error(translateUomError(e, t)); } finally { setLoading(false); } }, [user, search, t]);
  React.useEffect(() => { void load(); }, [load]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { const payload = { ...editing, name: editing.name, description: editing.description, decimal_precision: Number(editing.decimal_precision), allow_fraction: Boolean(editing.allow_fraction) }; if (editing.master_id) await putResource('uoms', editing.master_id, payload, user); else await postResource('uoms', payload, user); toast.success(t('uom.saved')); setEditing(null); await load(); } catch (e: any) { toast.error(translateUomError(e, t)); } };
  const remove = async () => { try { await deleteResource('uoms', confirm.master_id, user); toast.success(t('uom.deleted')); setConfirm(null); setActionMenuId(null); await load(); } catch (e: any) { toast.error(translateUomError(e, t)); } };
  const updateLifecycle = async (row: UomRecord, lifecycle_status: 'Inactive' | 'Released') => { try { await putResource('uoms', row.master_id, { lifecycle_status }, user); toast.success(t(lifecycle_status === 'Inactive' ? 'uom.deactivated' : 'uom.activated')); setActionMenuId(null); await load(); } catch (e: any) { toast.error(translateUomError(e, t)); } };
  return <div className="mes-page"><div className="mes-page-header"><div className="flex items-center gap-3"><div className="mes-icon-tile"><Ruler className="h-6 w-6" /></div><div><h1 className="text-xl font-bold text-foreground">{t('uom.title')}</h1><p className="text-xs text-muted-foreground">{t('uom.subtitle')}</p></div></div><div className="flex gap-2"><Button variant="secondary" size="icon" onClick={() => void load()}><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /></Button><Button onClick={() => setEditing(blank())}><Plus className="h-4 w-4" />{t('uom.create')}</Button></div></div>
    <Card className="p-4"><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={t('uom.search')} /><div className="mt-4 overflow-x-auto"><table className="mes-table"><thead><tr><th>{t('uom.code')}</th><th>{t('uom.name')}</th><th>{t('uom.type')}</th><th>{t('uom.precision')}</th><th>{t('uom.usage')}</th><th>{t('common.status')}</th><th className="text-right">{t('common.actions')}</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.master_id}><td className="font-mono font-bold">{row.code}</td><td>{uomLabel(row, text)}</td><td>{t(`uom.type.${row.uom_class}`)}</td><td>{row.decimal_precision} / {row.allow_fraction ? t('common.yes') : t('common.no')}</td><td>{row.usage_count || 0}</td><td>{t(`status.master.${row.lifecycle_status}`, { defaultValue: row.lifecycle_status })}</td><td className="relative text-right"><Button variant="ghost" size="icon" aria-label={t('uom.actions')} onClick={() => setActionMenuId(actionMenuId === row.master_id ? null : row.master_id)}><MoreHorizontal className="h-5 w-5" /></Button>{actionMenuId === row.master_id && <div className="absolute right-2 top-11 z-[120] min-w-44 rounded-md border border-border bg-surface p-1 text-left shadow-xl"><button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-foreground hover:bg-hover" onClick={() => { setDetail(row); setActionMenuId(null); }}><Eye className="h-4 w-4" />{t('uom.view')}</button><button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-foreground hover:bg-hover" onClick={() => { setEditing({ ...row, name: row.name || emptyLocalized(), description: row.description || emptyLocalized() }); setActionMenuId(null); }}><Pencil className="h-4 w-4" />{t('uom.edit')}</button>{row.lifecycle_status === 'Inactive' ? <button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-foreground hover:bg-hover" onClick={() => void updateLifecycle(row, 'Released')}><Power className="h-4 w-4" />{t('uom.activate')}</button> : Number(row.usage_count || 0) ? <button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-foreground hover:bg-hover" onClick={() => void updateLifecycle(row, 'Inactive')}><Power className="h-4 w-4" />{t('uom.deactivate')}</button> : <button type="button" className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-destructive hover:bg-destructive/10" onClick={() => { setConfirm(row); setActionMenuId(null); }}><Trash2 className="h-4 w-4" />{t('uom.delete')}</button>}</div>}</td></tr>)}</tbody></table></div></Card>
    <Modal open={Boolean(editing)} title={editing?.master_id ? t('uom.edit') : t('uom.create')} onClose={() => setEditing(null)} footer={<><Button variant="secondary" onClick={() => setEditing(null)}>{t('common.cancel')}</Button><Button onClick={(e) => void save(e as any)}>{t('common.save')}</Button></>}><form onSubmit={save} className="space-y-4"><label className="block text-sm">{t('uom.code')}<Input value={editing?.code || ''} readOnly={Boolean(editing?.master_id)} onChange={(e) => setEditing({ ...editing, code: e.target.value.toUpperCase() })} /></label><LocalizedTextFields label={t('uom.name')} value={editing?.name || emptyLocalized()} onChange={(name) => setEditing({ ...editing, name })} required /><LocalizedTextFields label={t('uom.description')} value={editing?.description || emptyLocalized()} onChange={(description) => setEditing({ ...editing, description })} multiline /><label className="block text-sm">{t('uom.type')}<SelectBase value={editing?.uom_class || 'Count'} onValueChange={(uom_class) => setEditing({ ...editing, uom_class })} options={TYPES.map((value) => ({ value, label: t(`uom.type.${value}`) }))} /></label><div className="grid grid-cols-2 gap-3"><DecimalInput label={t('uom.precision')} min="0" max="9" precision={0} integer value={String(editing?.decimal_precision ?? 0)} onValueChange={(value) => setEditing({ ...editing, decimal_precision: value === '' ? '' : Number(value) })} /><label className="flex items-center gap-2 pt-7 text-sm"><input type="checkbox" checked={Boolean(editing?.allow_fraction)} onChange={(e) => setEditing({ ...editing, allow_fraction: e.target.checked, decimal_precision: e.target.checked ? Math.max(1, Number(editing.decimal_precision)) : 0 })} />{t('uom.allowFraction')}</label></div></form></Modal>
    <Modal open={Boolean(detail)} title={detail ? uomLabel(detail, text) : ''} onClose={() => setDetail(null)}><p>{t('uom.usage')}: {detail?.usage_count || 0}</p><p>{t('uom.type')}: {detail && t(`uom.type.${detail.uom_class}`)}</p></Modal><Confirmation open={Boolean(confirm)} title={t('uom.delete')} description={t('common.confirm')} confirmLabel={t('uom.delete')} cancelLabel={t('common.cancel')} destructive onClose={() => setConfirm(null)} onConfirm={() => void remove()} />
  </div>;
};
