import './instrumentation.js';
import express, { type NextFunction, type Request, type Response } from 'express';
import { Pool } from 'pg';
import { OutboxRelayWorker } from '@mom-platform/shared-kernel';
import { runMigrations } from './infrastructure/db/migrate.js';
import { nonconformanceRouter } from './infrastructure/http/nonconformance.router.js';
import { registerEventSchemas } from './infrastructure/events/schema-registry.js';
import { InspectionFailureConsumer } from './infrastructure/events/inspection-consumer.js';

const PORT = Number(process.env['PORT'] ?? 3120); const DATABASE_URL = process.env['DATABASE_URL'] ?? 'postgresql://qms_nonconformance_user:qms_nonconformance_pass@localhost:15443/qms_nonconformance_db'; const MIGRATION_DATABASE_URL = process.env['MIGRATION_DATABASE_URL'] ?? DATABASE_URL; const BROKERS = (process.env['KAFKA_BROKERS'] ?? 'localhost:9092').split(','); const SCHEMA_URL = process.env['SCHEMA_REGISTRY_URL'] ?? 'http://localhost:18081';
async function wait(pool: Pool): Promise<void> { for (let i=0;i<15;i+=1) { try { await pool.query('SELECT 1'); return; } catch { await new Promise((r) => setTimeout(r, 2000)); } } throw new Error('Database never became ready'); }
async function bootstrap(): Promise<void> { const migrationPool = new Pool({ connectionString: MIGRATION_DATABASE_URL }); await wait(migrationPool); await runMigrations(migrationPool); const pool = MIGRATION_DATABASE_URL === DATABASE_URL ? migrationPool : new Pool({ connectionString: DATABASE_URL }); await wait(pool); try { await registerEventSchemas(SCHEMA_URL); } catch (e) { console.warn('[SchemaRegistry] Registration skipped:', e); } const relay = new OutboxRelayWorker({ pool, kafkaBrokers: BROKERS, clientId: 'qms-nonconformance-service', pollIntervalMs: 1000, batchSize: 50, maxRetries: 3 }); await relay.start(); const consumer = new InspectionFailureConsumer(pool, BROKERS); await consumer.start(); const app = express(); app.use(express.json({ limit: '1mb' })); app.get('/health', (_req,res) => res.json({ status:'ok', service:'qms-nonconformance-service', uptime:process.uptime() })); app.get('/metrics', (_req,res) => res.type('text/plain').send('# HELP qms_nonconformance_service_up Service health\n# TYPE qms_nonconformance_service_up gauge\nqms_nonconformance_service_up 1\n')); app.use('/api/qms/nonconformance', nonconformanceRouter(pool)); app.use((_req,res) => res.status(404).json({ error:'Not Found' })); app.use((e: Error & { statusCode?: number; errorCode?: string; code?: string }, _req: Request, res: Response, _next: NextFunction) => { const codes: Record<string,number> = {'23505':409,'23514':422,'23503':422}; console.error('[HTTP] Unhandled error:',e); res.status(e.statusCode ?? (e.code ? codes[e.code] : undefined) ?? 500).json({ error:e.errorCode ?? (e.statusCode ? e.message : 'Internal Server Error'), message:e.message }); }); const server = app.listen(PORT, () => console.info(`[Bootstrap] qms-nonconformance-service listening on :${PORT}`)); const shutdown = async () => { server.close(async () => { await consumer.stop(); await relay.stop(); await pool.end(); if (pool !== migrationPool) await migrationPool.end(); process.exit(0); }); setTimeout(() => process.exit(1),10000); }; process.on('SIGTERM', () => void shutdown()); process.on('SIGINT', () => void shutdown()); }
bootstrap().catch((e) => { console.error('[Bootstrap] Fatal error:', e); process.exit(1); });
