import React, { useMemo } from 'react';
import type { EChartsOption } from 'echarts';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { gatewayBaseUrl } from '../../lib/masterDataApi';
import { analyticsPalette, AnalyticsChartCard, AnalyticsEmptyState, AnalyticsErrorState, AnalyticsKpiCard, AnalyticsLegend, AnalyticsReportTable } from '../../components/analytics';
import { AnalyticsPageShell, analyticsHeaders, useAnalyticsFilters } from './AnalyticsPageShell';

type Overview = { kpis: Record<string, number>; production_trend: Array<{ date: string; planned_quantity: number; good_quantity: number; scrap_quantity: number }>; selection_breakdown: Array<{ selection: string; count: number }>; blocking_reasons: Array<{ reason: string; count: number }>; status_distribution: Array<{ status: string; count: number }> };
type WorkOrders = { data: Array<{ wo_id: string; wo_code: string; item_code: string; status: string; planned_quantity: number; selected_line_code?: string }> };

export const AnalyticsOverviewScreen: React.FC = () => {
  const { user } = useAuth(); const navigate = useNavigate(); const { filters, query, change, reset, search } = useAnalyticsFilters(); const headers = analyticsHeaders(user); const queryString = query.toString();
  const overview = useQuery({ queryKey: ['mes-analytics-overview', queryString], staleTime: 30_000, queryFn: async () => { const response = await fetch(`${gatewayBaseUrl()}/api/mes/execution/analytics/overview?${queryString}`, { headers }); if (!response.ok) throw new Error('overview'); return response.json() as Promise<Overview>; } });
  const orders = useQuery({ queryKey: ['mes-analytics-overview-orders', queryString], staleTime: 30_000, queryFn: async () => { const response = await fetch(`${gatewayBaseUrl()}/api/mes/execution/analytics/work-orders?${queryString}&page_size=200`, { headers }); if (!response.ok) throw new Error('orders'); return response.json() as Promise<WorkOrders>; } });
  const data = overview.data; const kpis = data?.kpis || {}; const trend = data?.production_trend || []; const selection = data?.selection_breakdown || []; const noData = !trend.some((row) => row.planned_quantity || row.good_quantity || row.scrap_quantity);
  const trendOption = useMemo<EChartsOption>(() => ({ tooltip: { trigger: 'axis' }, legend: { textStyle: { color: analyticsPalette.neutral } }, xAxis: { type: 'category', data: trend.map((row) => row.date), axisLabel: { color: analyticsPalette.neutral } }, yAxis: { type: 'value', name: 'Số lượng', axisLabel: { color: analyticsPalette.neutral } }, series: [{ name: 'Kế hoạch', type: 'line', smooth: true, data: trend.map((row) => row.planned_quantity), itemStyle: { color: analyticsPalette.primary } }, { name: 'Đạt', type: 'line', smooth: true, data: trend.map((row) => row.good_quantity), itemStyle: { color: analyticsPalette.success } }, { name: 'Lỗi', type: 'line', smooth: true, data: trend.map((row) => row.scrap_quantity), itemStyle: { color: analyticsPalette.danger } }] }), [trend]);
  const selectionOption = useMemo<EChartsOption>(() => ({ tooltip: { trigger: 'item' }, legend: { bottom: 0, textStyle: { color: analyticsPalette.neutral } }, series: [{ type: 'pie', radius: ['48%', '72%'], label: { color: analyticsPalette.neutral }, data: selection.map((row) => ({ name: row.selection === 'PRIMARY_PROXY' ? 'Primary (proxy)' : row.selection === 'BACKUP_PROXY' ? 'Backup (proxy)' : 'Resource Hold', value: row.count })) }] }), [selection]);
  const problemOption = useMemo<EChartsOption>(() => ({ tooltip: { trigger: 'axis' }, grid: { left: 125, right: 20, top: 12, bottom: 25 }, xAxis: { type: 'value', axisLabel: { color: analyticsPalette.neutral } }, yAxis: { type: 'category', inverse: true, data: (data?.blocking_reasons || []).map((row) => row.reason), axisLabel: { color: analyticsPalette.neutral, width: 110, overflow: 'truncate' } }, series: [{ type: 'bar', data: (data?.blocking_reasons || []).map((row) => row.count), itemStyle: { color: analyticsPalette.warning } }] }), [data?.blocking_reasons]);
  if (overview.isError || orders.isError) return <div className="mes-page"><AnalyticsErrorState onRetry={() => { void overview.refetch(); void orders.refetch(); }} /></div>;
  return <AnalyticsPageShell title="Phân tích sản xuất" subtitle="Tình trạng sản xuất hiện tại trong 5-10 giây, theo dữ liệu MES đã tổng hợp." filters={filters} onChange={change} onReset={reset} search={search} onRefresh={() => { void overview.refetch(); void orders.refetch(); }}>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[['active_work_orders', 'WO đang hoạt động', ''], ['completed_work_orders', 'WO hoàn thành', ''], ['blocked_work_orders', 'WO bị chặn', 'warning'], ['good_quantity', 'Sản lượng đạt', 'success'], ['scrap_rate', 'Tỷ lệ lỗi', 'danger'], ['fallback_rate_proxy', 'Fallback (proxy)', 'warning']].map(([key, label, tone]) => <AnalyticsKpiCard key={key} label={label} value={key.endsWith('rate_proxy') || key === 'scrap_rate' ? `${(((kpis[key] || 0) * 100)).toFixed(1)}%` : (kpis[key] || 0)} hint={key === 'fallback_rate_proxy' ? 'Vai trò line được suy ra từ fallback reason' : undefined} tone={tone as 'default' | 'warning' | 'danger' | 'success'} />)}</div>
    <div className="grid grid-cols-12 gap-4"><div className="col-span-12 lg:col-span-8"><AnalyticsChartCard title="Xu hướng Kế hoạch - Đạt - Lỗi" subtitle="Sản lượng theo ngày trong khoảng đã chọn" option={trendOption} loading={overview.isLoading} empty={noData} emptyMessage="Không có Work Order trong khoảng ngày này." /></div><div className="col-span-12 lg:col-span-4"><AnalyticsChartCard title="Primary / Backup / Resource Hold" subtitle="Backup và Primary là proxy theo fallback reason" option={selectionOption} loading={overview.isLoading} empty={!selection.length} /></div></div>
    <div className="grid grid-cols-12 gap-4"><div className="col-span-12 lg:col-span-7"><AnalyticsChartCard title="Vấn đề cần điều tra" subtitle="Top blocking/fallback reasons; click để mở report WO" option={problemOption} loading={overview.isLoading} empty={!data?.blocking_reasons.length} onClick={() => navigate('/analytics/production' + search)} /></div><div className="col-span-12 lg:col-span-5 rounded-md border border-border bg-card p-4"><h2 className="mb-3 text-sm font-bold">Tóm tắt sản lượng</h2><AnalyticsLegend items={[{ label: 'Kế hoạch', value: kpis.planned_quantity || 0, color: analyticsPalette.primary }, { label: 'Đạt', value: kpis.good_quantity || 0, color: analyticsPalette.success }, { label: 'Lỗi', value: kpis.scrap_quantity || 0, color: analyticsPalette.danger }]} /><div className="mt-5 text-sm text-muted-foreground">Tỷ lệ hoàn thành sản lượng: <b className="text-foreground">{(((kpis.completion_rate || 0) * 100)).toFixed(1)}%</b></div></div></div>
    <section className="rounded-md border border-border bg-card p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold">Work Order cần theo dõi</h2><button className="text-xs text-info hover:underline" onClick={() => navigate('/analytics/production' + search)}>Mở báo cáo đầy đủ</button></div><AnalyticsReportTable rows={orders.data?.data || []} onOpen={(id) => navigate(`/work-orders/${id}`)} /></section>
  </AnalyticsPageShell>;
};
