import { boolean, date, integer, jsonb, pgTable, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';
import type { LocalizedText } from '@mom-platform/shared-kernel';

export const qmsNcrNumberingRule = pgTable('qms_ncr_numbering_rule', {
  ruleId: uuid('rule_id').primaryKey().defaultRandom(), entityType: varchar('entity_type', { length: 10 }).notNull(), siteId: uuid('site_id').notNull(), prefix: varchar('prefix', { length: 12 }).notNull(), dateFormat: varchar('date_format', { length: 20 }).notNull().default('YYYYMMDD'), sequenceLength: integer('sequence_length').notNull().default(5),
}, (table) => ({ uqRuleScope: uniqueIndex('uq_qms_numbering_rule_scope').on(table.entityType, table.siteId) }));
export const qmsNcrNumberingSequence = pgTable('qms_ncr_numbering_sequence', { ruleId: uuid('rule_id').notNull().references(() => qmsNcrNumberingRule.ruleId), sequenceKey: varchar('sequence_key', { length: 50 }).notNull(), currentValue: integer('current_value').notNull().default(0), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ pk: uniqueIndex('uq_qms_numbering_sequence').on(table.ruleId, table.sequenceKey) }));
export const qmsNcr = pgTable('qms_ncr', {
  ncrId: uuid('ncr_id').primaryKey().defaultRandom(), ncrCode: varchar('ncr_code', { length: 80 }).notNull().unique(), source: varchar('source', { length: 30 }).notNull(), sourceResultId: uuid('source_result_id'), sourceEventId: uuid('source_event_id').unique(), itemRevisionId: uuid('item_revision_id'), workOrderId: uuid('work_order_id'), workCenterId: uuid('work_center_id'), lotOrLabelRef: varchar('lot_or_label_ref', { length: 120 }), siteId: uuid('site_id').notNull(), severity: varchar('severity', { length: 20 }).notNull(), description: jsonb('description').$type<LocalizedText>().notNull(), status: varchar('status', { length: 20 }).notNull().default('Open'), raisedByUserId: uuid('raised_by_user_id').notNull(), raisedAt: timestamp('raised_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), rowVersion: integer('row_version').notNull().default(1),
});
export const qmsNcrDisposition = pgTable('qms_ncr_disposition', { dispositionId: uuid('disposition_id').primaryKey().defaultRandom(), ncrId: uuid('ncr_id').notNull().references(() => qmsNcr.ncrId), dispositionType: varchar('disposition_type', { length: 30 }).notNull(), reason: jsonb('reason').$type<LocalizedText>().notNull(), decidedByUserId: uuid('decided_by_user_id').notNull(), decidedAt: timestamp('decided_at', { withTimezone: true }).notNull().defaultNow(), requiresCapa: boolean('requires_capa').notNull().default(false), activeFlag: boolean('active_flag').notNull().default(true), supersededAt: timestamp('superseded_at', { withTimezone: true }) });
export const qmsCapa = pgTable('qms_capa', { capaId: uuid('capa_id').primaryKey().defaultRandom(), capaCode: varchar('capa_code', { length: 80 }).notNull().unique(), rootCause: jsonb('root_cause').$type<LocalizedText>().notNull(), actionPlan: jsonb('action_plan').$type<LocalizedText>().notNull(), ownerUserId: uuid('owner_user_id').notNull(), dueDate: date('due_date').notNull(), status: varchar('status', { length: 20 }).notNull().default('Open'), verifiedByUserId: uuid('verified_by_user_id'), verifiedAt: timestamp('verified_at', { withTimezone: true }), samePersonVerificationFlag: boolean('same_person_verification_flag').notNull().default(false), createdByUserId: uuid('created_by_user_id').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), rowVersion: integer('row_version').notNull().default(1) });
export const qmsCapaNcrLink = pgTable('qms_capa_ncr_link', { capaId: uuid('capa_id').notNull().references(() => qmsCapa.capaId), ncrId: uuid('ncr_id').notNull().references(() => qmsNcr.ncrId), linkedAt: timestamp('linked_at', { withTimezone: true }).notNull().defaultNow(), linkedByUserId: uuid('linked_by_user_id').notNull() }, (table) => ({ uqLink: uniqueIndex('uq_qms_capa_ncr_link').on(table.capaId, table.ncrId) }));
