import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { useI18n } from '@mom-platform/i18n-ui-shared';
import { api, type Row } from '../lib/api/client';
import { Button, Card, CardContent, CardHeader, CardTitle, Badge } from '../components/ui';
import { ConfirmActionDialog } from '../components/shared/ConfirmActionDialog';

const text = (value: any, locale: string) => typeof value === 'object' ? value?.[locale] || value?.vi || value?.en || '-' : value ?? '-';
export function PlanDetailPage() { const { id } = useParams(); const navigate = useNavigate(); const { t } = useI18n(); const [row, setRow] = useState<Row | null>(null); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); useEffect(() => { if (id) api.plan(id).then((result) => setRow(result.data)).catch(() => undefined); }, [id]); if (!row) return <div className="animate-pulse rounded-md border bg-card p-8 text-sm text-muted-foreground">{t('common.loading')}</div>; const release = async () => { setBusy(true); setError(''); try { const result = await api.releasePlan(id!); setRow(result.data); setOpen(false); toast.success(t('common.save')); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }; return <><div className="mb-5 flex items-start justify-between gap-3"><div><h1 className="text-2xl font-black">{row.plan_code}</h1><p className="mt-1 text-sm text-muted-foreground">{text(row.plan_name, 'vi')}</p></div><Button variant="outline" onClick={() => navigate(-1)}>{t('common.back')}</Button></div><Card><CardHeader><CardTitle>{t('nav.plans')}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Badge variant="outline">{t(`status.${row.status}`)}</Badge><span className="text-sm text-muted-foreground">{row.characteristics?.length ?? 0} {t('result.characteristics')}</span></div><div className="space-y-2">{(row.characteristics ?? []).map((item: Row) => <div key={item.characteristic_id} className="rounded-md border p-3"><div className="font-semibold">{text(item.characteristic_name, 'vi')}</div><div className="text-xs text-muted-foreground">{item.characteristic_code} · {item.measurement_type}</div></div>)}</div>{row.status !== 'Released' ? <Button onClick={() => { setError(''); setOpen(true); }}>{t('plan.release')}</Button> : null}</CardContent></Card><ConfirmActionDialog open={open} onOpenChange={setOpen} loading={busy} error={error} title={t('confirm.plan.title')} body={t('confirm.plan.body')} confirmLabel={t('plan.release')} cancelLabel={t('common.cancel')} onConfirm={() => void release()} /></>; }
