import React from 'react';
import { ExternalLink, X } from 'lucide-react';
import { useI18n } from '@mom-platform/i18n-ui-shared';
import { translatedEnum } from '../../lib/i18nLabels';
import { localizedText } from './workOrderDetail';

export function WorkOrderDetailModal({ wo, onClose, onOpen }: { wo: any; onClose: () => void; onOpen: () => void }) {
  const { t, formatDate } = useI18n();
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4" role="dialog" aria-modal="true" aria-labelledby="wo-detail-modal-title">
    <div className="max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-lg border border-border bg-surface shadow-2xl">
      <div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-surface px-6 py-4"><div><h2 id="wo-detail-modal-title" className="font-mono text-xl font-bold text-action">{wo.wo_code}</h2><p className="text-sm text-muted-foreground">{localizedText(wo.item_name) || wo.item_code}</p></div><div className="flex items-center gap-2"><button type="button" onClick={onOpen} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-sm font-semibold hover:bg-hover"><ExternalLink className="h-4 w-4" />{t('common.detail')}</button><button type="button" onClick={onClose} className="rounded-md p-2 hover:bg-hover" aria-label={t('common.close')}><X className="h-5 w-5" /></button></div></div>
      <div className="space-y-6 p-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[t('productionVersion.itemCode'), wo.item_code], [t('wo.quantity'), `${wo.quantity} ${wo.uom || t('uom.pcs')}`], [t('workOrders.create.fields.site'), wo.site_code || wo.site_name || t('common.notAvailable')], [t('common.status'), translatedEnum(t, 'status.wo', wo.status)]].map(([label, value]) => <div key={String(label)} className="rounded-md border border-border bg-surface-subtle p-3"><div className="text-xs font-semibold uppercase text-muted-foreground">{label}</div><div className="mt-1 font-semibold text-foreground">{value}</div></div>)}</div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-md border border-border bg-surface-subtle p-3"><div className="text-xs font-semibold uppercase text-muted-foreground">{t('woCreate.targetStart')}</div><div className="mt-1 font-semibold text-foreground">{wo.planned_start_date ? formatDate(wo.planned_start_date) : t('common.notAvailable')}</div></div><div className="rounded-md border border-border bg-surface-subtle p-3"><div className="text-xs font-semibold uppercase text-muted-foreground">{t('wo.targetDate')}</div><div className="mt-1 font-semibold text-foreground">{wo.target_completion_date ? formatDate(wo.target_completion_date) : t('common.notAvailable')}</div></div></div>
        <section><h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-muted-foreground">{t('woDetail.operationsTitle')}</h3><div className="overflow-x-auto rounded-md border border-border"><table className="w-full text-left text-sm"><thead className="bg-surface-subtle text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">{t('mbom.seq')}</th><th className="px-4 py-3">{t('woDetail.operationName')}</th><th className="px-4 py-3">{t('woDetail.assignedWorkCenter')}</th><th className="px-4 py-3">{t('common.status')}</th></tr></thead><tbody className="divide-y divide-border">{wo.operations.length ? wo.operations.map((op: any, index: number) => <tr key={op.wo_operation_id || index}><td className="px-4 py-3 font-mono">{op.sequence || op.seq || (index + 1) * 10}</td><td className="px-4 py-3">{localizedText(op.operation_name) || t(`operation.${op.operation_code}`)} <span className="text-muted-foreground">({op.operation_code || t('common.notAvailable')})</span></td><td className="px-4 py-3">{op.work_center || op.work_center_code || t('common.notAvailable')}</td><td className="px-4 py-3">{translatedEnum(t, 'operation.status', op.status || 'READY')}</td></tr>) : <tr><td colSpan={4} className="px-4 py-6 text-center text-muted-foreground">{t('common.notAvailable')}</td></tr>}</tbody></table></div></section>
        <section><h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-muted-foreground">{t('woDetail.materialRequirementsTitle')}</h3><div className="overflow-x-auto rounded-md border border-border"><table className="w-full text-left text-sm"><thead className="bg-surface-subtle text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">{t('woDetail.material')}</th><th className="px-4 py-3">{t('woDetail.requiredQty')}</th><th className="px-4 py-3">{t('common.status')}</th><th className="px-4 py-3">WMS</th></tr></thead><tbody className="divide-y divide-border">{wo.material_requirements.length ? wo.material_requirements.map((row: any) => <tr key={row.requirement_id}><td className="px-4 py-3">{row.component_item_code || t('common.notAvailable')}</td><td className="px-4 py-3">{row.required_qty}</td><td className="px-4 py-3">{translatedEnum(t, 'materialRequest.status', row.stock_check_status || 'NotChecked')}</td><td className="px-4 py-3 text-xs text-muted-foreground">{row.wms_request_code || row.wms_status || row.wms_detail || t('common.notAvailable')}</td></tr>) : <tr><td colSpan={4} className="px-4 py-6 text-center text-muted-foreground">{t('woDetail.noMaterialRequirements')}</td></tr>}</tbody></table></div></section><section><h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-muted-foreground">{t('woDetail.approvalHistory')}</h3><div className="space-y-2">{wo.approval_logs.length ? wo.approval_logs.map((log: any, index: number) => <div key={log.approval_log_id || index} className="rounded-md border border-border bg-surface-subtle p-3 text-sm"><div className="flex justify-between gap-3 font-semibold"><span>{log.action || log.status || t('common.notAvailable')}</span><span className="text-xs text-muted-foreground">{log.created_at ? formatDate(log.created_at) : ''}</span></div><div className="mt-1 text-muted-foreground">{log.comment || log.reason || t('common.notAvailable')}</div></div>) : <p className="text-sm text-muted-foreground">{t('common.notAvailable')}</p>}</div></section></div>
    </div></div>;
}
