import { Router, type NextFunction, type Request } from 'express';
import { Pool } from 'pg';
import { localizedTextSchema, createEventEnvelope, writeToOutbox } from '@mom-platform/shared-kernel';
import { allocateCode, error, publishNcrRaised, SERVICE_NAME } from '../../domain/case-service.js';

const SYSTEM_USER_ID = '00000000-0000-0000-0000-000000000001';
type Ctx = { userId: string; roleCode: string; traceId: string };
const ctx = (req: Request): Ctx => ({ userId: String(req.headers['x-user-id'] ?? SYSTEM_USER_ID), roleCode: String(req.headers['x-role-code'] ?? 'UNKNOWN'), traceId: String(req.headers['x-trace-id'] ?? 'missing-trace') });
const body = (value: unknown): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw error('JSON object body is required'); return value as Record<string, unknown>; };
const localized = (value: unknown, field: string): unknown => { const parsed = localizedTextSchema.safeParse(value); if (!parsed.success) throw error(`${field} must be LocalizedText with a non-empty vi value`); return parsed.data; };
const requireRole = (req: Request, roles: string[]) => { if (!roles.includes(ctx(req).roleCode)) throw error('Role is not allowed for this operation', 403, 'FORBIDDEN'); };

export function nonconformanceRouter(pool: Pool): Router {
  const router = Router();
  router.get('/ncr', async (req, res, next) => { try { const values: unknown[] = []; const where: string[] = []; for (const [key, column] of [['status','n.status'],['severity','n.severity'],['source','n.source'],['item_revision_id','n.item_revision_id'],['work_order_id','n.work_order_id']] as const) if (typeof req.query[key] === 'string') { values.push(req.query[key]); where.push(`${column}=$${values.length}`); } const { rows } = await pool.query(`SELECT n.* FROM qms_ncr n ${where.length ? `WHERE ${where.join(' AND ')}` : ''} ORDER BY n.raised_at DESC LIMIT 500`, values); res.json({ data: rows }); } catch (e) { return next(e); } });
  router.get('/ncr/:id', async (req, res, next) => { try { const ncr = await pool.query('SELECT * FROM qms_ncr WHERE ncr_id=$1', [req.params['id']]); if (!ncr.rows[0]) return res.status(404).json({ error: 'Not Found' }); const dispositions = await pool.query('SELECT * FROM qms_ncr_disposition WHERE ncr_id=$1 ORDER BY decided_at DESC', [req.params['id']]); const links = await pool.query('SELECT l.* FROM qms_capa_ncr_link l WHERE l.ncr_id=$1', [req.params['id']]); return res.json({ data: { ...ncr.rows[0], dispositions: dispositions.rows, capa_links: links.rows } }); } catch (e) { return next(e); } });
  router.post('/ncr', async (req, res, next) => { try { requireRole(req, ['QC_TECHNICIAN', 'PLANT_MANAGER']); const b = body(req.body); const c = ctx(req); const description = localized(b['description'], 'description'); const severity = String(b['severity'] ?? ''); if (!['Critical','Major','Minor'].includes(severity)) throw error('severity must be Critical, Major, or Minor'); const siteId = String(b['site_id'] ?? ''); if (siteId.length < 10) throw error('site_id is required'); const client = await pool.connect(); try { await client.query('BEGIN'); await client.query(`SELECT pg_advisory_xact_lock(hashtext($1))`, [`manual-ncr-${siteId}-${Date.now()}-${c.userId}`]); const code = await allocateCode(client, 'NCR', siteId); const row = (await client.query(`INSERT INTO qms_ncr (ncr_code,source,source_result_id,source_event_id,item_revision_id,work_order_id,work_center_id,lot_or_label_ref,site_id,severity,description,status,raised_by_user_id) VALUES ($1,'Manual',$2,$3,$4,$5,$6,$7,$8,$9,$10,'Open',$11) RETURNING *`, [code, b['source_result_id'] ?? null, b['source_event_id'] ?? null, b['item_revision_id'] ?? null, b['work_order_id'] ?? null, b['work_center_id'] ?? null, b['lot_or_label_ref'] ?? null, siteId, severity, JSON.stringify(description), c.userId])).rows[0] as Record<string, unknown>; await publishNcrRaised(client, c.traceId, row); await client.query('COMMIT'); return res.status(201).json({ data: row }); } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } } catch (e) { return next(e); } });
  router.patch('/ncr/:id', async (req, res, next) => { try { requireRole(req, ['QC_TECHNICIAN', 'PLANT_MANAGER']); const b = body(req.body); const c = ctx(req); const fields: string[] = []; const values: unknown[] = []; if (b['description'] !== undefined) { fields.push('description'); values.push(JSON.stringify(localized(b['description'], 'description'))); } if (b['status'] !== undefined) { if (!['Open','UnderReview'].includes(String(b['status']))) throw error('Only Open and UnderReview may be updated directly', 422); fields.push('status'); values.push(b['status']); } if (!fields.length) throw error('No update fields provided'); values.push(req.params['id']); const { rows } = await pool.query(`UPDATE qms_ncr SET ${fields.map((f,i) => `${f}=$${i+1}`).join(',')},updated_at=NOW(),row_version=row_version+1 WHERE ncr_id=$${values.length} RETURNING *`, values); if (!rows[0]) return res.status(404).json({ error: 'Not Found' }); return res.json({ data: rows[0], trace_id: c.traceId }); } catch (e) { return next(e); } });
  router.post('/ncr/:id/disposition', async (req, res, next) => { try { requireRole(req, ['PLANT_MANAGER','EXECUTIVE']); const b = body(req.body); const c = ctx(req); const type = String(b['disposition_type'] ?? ''); if (!['UseAsIs','Rework','Scrap','ReturnToSupplier'].includes(type)) throw error('Invalid disposition_type'); const reason = localized(b['reason'], 'reason'); const client = await pool.connect(); try { await client.query('BEGIN'); const ncr = (await client.query('SELECT * FROM qms_ncr WHERE ncr_id=$1 FOR UPDATE', [req.params['id']])).rows[0] as Record<string, unknown> | undefined; if (!ncr) { await client.query('ROLLBACK'); return res.status(404).json({ error: 'Not Found' }); } if (ncr['status'] === 'Closed') { await client.query('ROLLBACK'); return res.status(409).json({ error: 'NCR_ALREADY_CLOSED' }); } await client.query('UPDATE qms_ncr_disposition SET active_flag=FALSE,superseded_at=NOW() WHERE ncr_id=$1 AND active_flag=TRUE', [req.params['id']]); const disposition = (await client.query(`INSERT INTO qms_ncr_disposition (ncr_id,disposition_type,reason,decided_by_user_id,requires_capa) VALUES ($1,$2,$3::jsonb,$4,$5) RETURNING *`, [req.params['id'], type, JSON.stringify(reason), c.userId, b['requires_capa'] === true])).rows[0] as Record<string, unknown>; const newStatus = disposition['requires_capa'] ? 'CAPARequired' : 'Dispositioned'; const updated = (await client.query('UPDATE qms_ncr SET status=$1,updated_at=NOW(),row_version=row_version+1 WHERE ncr_id=$2 RETURNING *', [newStatus, req.params['id']])).rows[0] as Record<string, unknown>; await writeToOutbox(client, { topic: 'QMS.Nonconformance.NCRDispositioned.v1', envelope: createEventEnvelope({ event_type: 'QMS.Nonconformance.NCRDispositioned.v1', source_service: SERVICE_NAME, trace_id: c.traceId, payload: { ncr_id: updated['ncr_id'], ncr_code: updated['ncr_code'], item_revision_id: updated['item_revision_id'], work_order_id: updated['work_order_id'], work_center_id: updated['work_center_id'], lot_or_label_ref: updated['lot_or_label_ref'], disposition_type: disposition['disposition_type'], requires_capa: disposition['requires_capa'], status: updated['status'] } }) }); await client.query('COMMIT'); return res.json({ data: { ncr: updated, disposition } }); } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } } catch (e) { return next(e); } });

  router.get('/capa', async (req, res, next) => { try { const values: unknown[] = []; const where: string[] = []; if (typeof req.query['status'] === 'string') { values.push(req.query['status']); where.push(`c.status=$${values.length}`); } const { rows } = await pool.query(`SELECT c.* FROM qms_capa c ${where.length ? `WHERE ${where.join(' AND ')}` : ''} ORDER BY c.created_at DESC LIMIT 500`, values); res.json({ data: rows }); } catch (e) { return next(e); } });
  router.get('/capa/:id', async (req, res, next) => { try { const capa = await pool.query('SELECT * FROM qms_capa WHERE capa_id=$1', [req.params['id']]); if (!capa.rows[0]) return res.status(404).json({ error: 'Not Found' }); const links = await pool.query('SELECT l.*, n.ncr_code, n.status AS ncr_status FROM qms_capa_ncr_link l JOIN qms_ncr n ON n.ncr_id=l.ncr_id WHERE l.capa_id=$1', [req.params['id']]); return res.json({ data: { ...capa.rows[0], ncr_links: links.rows } }); } catch (e) { return next(e); } });
  router.post('/capa', async (req, res, next) => { try { requireRole(req, ['QC_TECHNICIAN','PLANT_MANAGER']); const b = body(req.body); const c = ctx(req); const siteId = String(b['site_id'] ?? ''); const rootCause = localized(b['root_cause'], 'root_cause'); const actionPlan = localized(b['action_plan'], 'action_plan'); if (siteId.length < 10 || !b['owner_user_id'] || !b['due_date']) throw error('site_id, owner_user_id, and due_date are required'); const client = await pool.connect(); try { await client.query('BEGIN'); const code = await allocateCode(client, 'CAPA', siteId); const row = (await client.query(`INSERT INTO qms_capa (capa_code,root_cause,action_plan,owner_user_id,due_date,created_by_user_id) VALUES ($1,$2::jsonb,$3::jsonb,$4,$5,$6) RETURNING *`, [code, JSON.stringify(rootCause), JSON.stringify(actionPlan), b['owner_user_id'], b['due_date'], c.userId])).rows[0]; await client.query('COMMIT'); return res.status(201).json({ data: row }); } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } } catch (e) { return next(e); } });
  router.patch('/capa/:id', async (req, res, next) => { try { requireRole(req, ['QC_TECHNICIAN','PLANT_MANAGER']); const b = body(req.body); const fields: string[] = []; const values: unknown[] = []; for (const [key, column] of [['root_cause','root_cause'],['action_plan','action_plan'],['owner_user_id','owner_user_id'],['due_date','due_date'],['status','status']] as const) if (b[key] !== undefined) { if (key === 'root_cause' || key === 'action_plan') values.push(JSON.stringify(localized(b[key], key))); else values.push(b[key]); fields.push(column); } if (!fields.length) throw error('No update fields provided'); if (b['status'] === 'Closed' || b['status'] === 'Verified') throw error('Use verify or close endpoint for CAPA status transitions', 422); values.push(req.params['id']); const { rows } = await pool.query(`UPDATE qms_capa SET ${fields.map((f,i) => `${f}=$${i+1}`).join(',')},updated_at=NOW(),row_version=row_version+1 WHERE capa_id=$${values.length} AND status IN ('Open','InProgress') RETURNING *`, values); if (!rows[0]) return res.status(409).json({ error: 'CAPA_NOT_EDITABLE_OR_NOT_FOUND' }); return res.json({ data: rows[0] }); } catch (e) { return next(e); } });
  router.post('/capa/:id/link-ncr', async (req, res, next) => { try { requireRole(req, ['QC_TECHNICIAN','PLANT_MANAGER']); const c = ctx(req); const ncrId = String(body(req.body)['ncr_id'] ?? ''); if (ncrId.length < 10) throw error('ncr_id is required'); const { rows } = await pool.query('INSERT INTO qms_capa_ncr_link (capa_id,ncr_id,linked_by_user_id) VALUES ($1,$2,$3) ON CONFLICT (capa_id,ncr_id) DO NOTHING RETURNING *', [req.params['id'], ncrId, c.userId]); if (!rows[0]) return res.status(409).json({ error: 'NCR_ALREADY_LINKED_OR_NOT_FOUND' }); return res.status(201).json({ data: rows[0] }); } catch (e) { return next(e); } });
  router.post('/capa/:id/verify', async (req, res, next) => { try { requireRole(req, ['PLANT_MANAGER','EXECUTIVE']); const c = ctx(req); const { rows } = await pool.query(`UPDATE qms_capa SET status='Verified',verified_by_user_id=$1,verified_at=NOW(),same_person_verification_flag=(owner_user_id=$1),updated_at=NOW(),row_version=row_version+1 WHERE capa_id=$2 AND status IN ('Open','InProgress') RETURNING *`, [c.userId, req.params['id']]); if (!rows[0]) return res.status(409).json({ error: 'CAPA_NOT_VERIFIABLE_OR_NOT_FOUND' }); return res.json({ data: rows[0] }); } catch (e) { return next(e); } });
  router.post('/capa/:id/close', async (req, res, next) => { try { requireRole(req, ['PLANT_MANAGER','EXECUTIVE']); const c = ctx(req); const client = await pool.connect(); try { await client.query('BEGIN'); const row = (await client.query(`UPDATE qms_capa SET status='Closed',updated_at=NOW(),row_version=row_version+1 WHERE capa_id=$1 AND status='Verified' RETURNING *`, [req.params['id']])).rows[0] as Record<string, unknown> | undefined; if (!row) { await client.query('ROLLBACK'); return res.status(409).json({ error: 'CAPA_MUST_BE_VERIFIED_BEFORE_CLOSE' }); } await writeToOutbox(client, { topic: 'QMS.Nonconformance.CAPAClosed.v1', envelope: createEventEnvelope({ event_type: 'QMS.Nonconformance.CAPAClosed.v1', source_service: SERVICE_NAME, trace_id: c.traceId, payload: { capa_id: row['capa_id'], capa_code: row['capa_code'], status: row['status'], owner_user_id: row['owner_user_id'], verified_by_user_id: row['verified_by_user_id'] } }) }); await client.query('COMMIT'); return res.json({ data: row }); } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } } catch (e) { return next(e); } });
  return router;
}
